apiVersion: apps/v1
kind: Deployment
metadata: 
  name: driver-deployment
  labels:
    app: driver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: driver
  template:
    metadata:
      labels:
        app: driver
    spec:
      containers:
      - name: driver
        image: driver-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: eureka.instance.preferIpAddress
          value: 'true'
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: databases-configmap
              key: driverdb-name
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: databases-secrets
              key: driverdb-username
        - name: POSTGRES_PASSWORD
          valueFrom:
              secretKeyRef:
                name: databases-secrets
                key: driverdb-password
