apiVersion: apps/v1
kind: Deployment
metadata: 
  name: zookeeper-deployment
  labels:
    app: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: confluentinc/cp-zookeeper:7.4.4
        imagePullPolicy: Never
        ports:
        - containerPort: 2181
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          valueFrom:
            configMapKeyRef:
              name: kafka-configmap
              key: zookeeper-client-port
        - name: ZOOKEEPER_TICK_TIME
          valueFrom:
            configMapKeyRef:
              name: kafka-configmap
              key: zookeeper-tick-time
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
spec:
  selector:
    app: zookeeper
  ports:
    - protocol: TCP
      port: 2181
      targetPort: 2181
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: kafka-deployment
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka-broker
        image: confluentinc/cp-kafka:7.4.4
        imagePullPolicy: Never
        ports:
        - containerPort: 9092
        env:        
          - name: KAFKA_BROKER_ID
            valueFrom:
              configMapKeyRef:
                name: kafka-configmap
                key: kafka-broker-id
          - name: KAFKA_ZOOKEEPER_CONNECT
            valueFrom:
              configMapKeyRef:
                name: kafka-configmap
                key: kafka-zookeeper-connect
          - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
            valueFrom:
              configMapKeyRef:
                name: kafka-configmap
                key: kafka-auto-create-topics-enable
          - name: KAFKA_ADVERTISED_LISTENERS
            valueFrom:
              configMapKeyRef:
                name: kafka-configmap
                key: kafka-advertised-listeners
          - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
            valueFrom:
              configMapKeyRef:
                name: kafka-configmap
                key: kafka-listener-security-protocol-map
          - name: KAFKA_INTER_BROKER_LISTENER_NAME
            valueFrom:
              configMapKeyRef:
                name: kafka-configmap
                key: kafka-inter-broker-listener-name
          - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
            valueFrom:
              configMapKeyRef:
                name: kafka-configmap
                key: kafka-offsets-topic-replication-factor
       
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-container
spec:
  selector:
    app: kafka
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
