apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-configmap
data:
  zookeeper-client-port: '2181'
  zookeeper-tick-time: '2000'
  kafka-broker-id: '1'
  kafka-zookeeper-connect: 'zookeeper-service:2181'
  kafka-auto-create-topics-enable: 'true'
  kafka-advertised-listeners: 'PLAINTEXT://kafka-container:9092,PLAINTEXT_HOST://localhost:29092'
  kafka-listener-security-protocol-map: 'PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
  kafka-inter-broker-listener-name: 'PLAINTEXT'
  kafka-offsets-topic-replication-factor: '1'