apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    scrape_configs:
      - job_name: 'passenger-service'
        metrics_path: '/actuator/prometheus'
        scrape_interval: 5s
        static_configs:
        - targets: ['passenger-service:8080']
      - job_name: 'driver-service'
        metrics_path: '/actuator/prometheus'
        scrape_interval: 5s
        static_configs:
        - targets: ['driver-service:8080']
      - job_name: 'rating-service'
        metrics_path: '/actuator/prometheus'
        scrape_interval: 5s
        static_configs:
        - targets: ['rating-service:8080']
      - job_name: 'ride-service'
        metrics_path: '/actuator/prometheus'
        scrape_interval: 5s
        static_configs:
        - targets: ['ride-service:8080']
      - job_name: 'kafka'
        scrape_interval: 5s
        static_configs:
        - targets: ['kafka-container:7071']

