apiVersion: apps/v1
kind: Deployment
metadata: 
  name: rating-deployment
  labels:
    app: rating
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rating
  template:
    metadata:
      labels:
        app: rating
    spec:
      containers:
      - name: rating
        image: rating-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: eureka.instance.preferIpAddress
          value: 'true'
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: databases-configmap
              key: ratingdb-name
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: databases-secrets
              key: ratingdb-username
        - name: POSTGRES_PASSWORD
          valueFrom:
              secretKeyRef:
                name: databases-secrets
                key: ratingdb-password
