apiVersion: apps/v1
kind: Deployment
metadata: 
  name: ratingdb-deployment
  labels:
    app: ratingdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratingdb
  template:
    metadata:
      labels:
        app: ratingdb
    spec:
      containers:
      - name: ratingdb
        image: postgres:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: databases-configmap
              key: ratingdb-name
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: databases-secrets
              key: ratingdb-username
        - name: POSTGRES_PASSWORD
          valueFrom:
              secretKeyRef:
                name: databases-secrets
                key: ratingdb-password
---
apiVersion: v1
kind: Service
metadata:
  name: ratingdb-service
spec:
  selector:
    app: ratingdb
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
